//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Note
    {
        public int UserId { get; set; }
        public Nullable<int> FilmId { get; set; }
        public string NoteTitle { get; set; }
        public string Text { get; set; }
        public Nullable<System.DateTime> DateOfCreation { get; set; }
        public Nullable<int> Rating { get; set; }
    }
}
